# SPDX-License-Identifier: BSD-3-Clause
"""
Usermode build configuration.

Sets up the usermode environment with musl libc support and builds
all userspace libraries and applications.
"""

import os

from SCons.Environment import Environment
from SCons.Script import Export

from scripts.scons.arch import GetArchConfig

Import('TargetEnvironment')
Import('RuntimeDependencies')
TargetEnvironment: Environment


# =============================================================================
# Usermode Environment Setup
# =============================================================================

Architecture = TargetEnvironment['build.arch']
ArchitectureConfig = GetArchConfig(Architecture)
RuntimeSysroot = os.path.abspath(str(
    TargetEnvironment.get(
        'RuntimeDependencySysroot',
        TargetEnvironment.get('RuntimeDependencyMuslDirectory', ''),
    )
))

UsermodeEnv = TargetEnvironment.Clone()
UsermodeEnv.Append(
    CPPDEFINES=['_POSIX_C_SOURCE=200809L'],  # POSIX.1-2008
    CCFLAGS=[f'--sysroot={RuntimeSysroot}'],
    LINKFLAGS=[f'--sysroot={RuntimeSysroot}'],
)

UsermodeEnv.Append(
    ASFLAGS=ArchitectureConfig.get('AssemblyFlags', []),
    CCFLAGS=ArchitectureConfig.get('CompilerFlags', []),
    LINKFLAGS=ArchitectureConfig.get('LinkerFlags', []),
)

UsermodeEnv['SHLIBPREFIX'] = 'lib'
UsermodeEnv['SHLIBSUFFIX'] = '.so'

Export('UsermodeEnv')
Export('RuntimeDependencies')


# =============================================================================
# Build Sub-projects
# =============================================================================

SConscript('libmath/SConscript', variant_dir='libmath_build', duplicate=0)
SConscript('sh/SConscript', variant_dir='sh_build', duplicate=0)
SConscript('selftest/SConscript', variant_dir='selftest_build', duplicate=0)


# =============================================================================
# Export Build Products
# =============================================================================

Import('LibmathModule')
Import('ShModule')
Import('SelftestModule')

UserLibraries = [LibmathModule]
UserApplications = [ShModule, SelftestModule]

Export('UserLibraries')
Export('UserApplications')
