# SPDX-License-Identifier: BSD-3-Clause
"""
selftest - Freestanding user-mode syscall test application build configuration.
"""

from SCons.Script import Dir, Export

from scripts.scons.utility import GlobSources

Import('UsermodeEnv')
Import('RuntimeDependencies')

Env = UsermodeEnv.Clone()

Srcpath = Dir('#usr/selftest').abspath

Env.Append(
    CPATH=[Srcpath],
    CPPPATH=[Srcpath],
    CCFLAGS=['-ffreestanding', '-fno-builtin', '-fno-pie', '-fno-stack-protector'],
    LINKFLAGS=['-nostdlib', '-nostartfiles', '-nodefaultlibs', '-static', '-Wl,-e,_start', '-no-pie'],
)

Sources = GlobSources(Srcpath)
Objects = Env.Object(Sources)
Env.Depends(Objects, RuntimeDependencies)

SelftestExecutable = Env.Program('selftest', Objects)

SelftestModule = SelftestExecutable
Export('SelftestModule')
