# SPDX-License-Identifier: BSD-3-Clause
"""
selftest - Freestanding user-mode syscall test application build configuration.
"""

from SCons.Script import Dir, Export

from scripts.scons.utility import GlobSources

Import('usermode_env')
Import('runtime_dependencies')

env = usermode_env.Clone()

srcpath = Dir('#usr/selftest').abspath

env.Append(
    CPATH=[srcpath],
    CPPPATH=[srcpath],
    CCFLAGS=['-ffreestanding', '-fno-builtin', '-fno-pie', '-fno-stack-protector'],
    LINKFLAGS=['-nostdlib', '-nostartfiles', '-nodefaultlibs', '-static', '-Wl,-e,_start', '-no-pie'],
)

sources = GlobSources(srcpath)
objects = env.Object(sources)
env.Depends(objects, runtime_dependencies)

selftest_executable = env.Program('selftest', objects)

selftest_module = selftest_executable
Export('selftest_module')
