# SPDX-License-Identifier: BSD-3-Clause
"""
libmath - Math library build configuration.
"""

from SCons.Script import Dir, Export

from scripts.scons.utility import GlobSources

Import('usermode_env')
Import('runtime_dependencies')

env = usermode_env.Clone()

srcpath = Dir('#usr/libmath').abspath

# Shared library compilation flags
env.Append(
    CCFLAGS=['-fPIC'],
    CFLAGS=['-fPIC'],
    CXXFLAGS=['-fPIC'],
    LINKFLAGS=[
        '-shared',
        '-Wl,-soname,libmath.so',
    ],
    CPATH=[srcpath],
    CPPPATH=[srcpath],
    ASFLAGS=['-I', srcpath + '/', '-f', 'elf'],
)

sources = GlobSources(srcpath)
objects = env.SharedObject(sources)
env.Depends(objects, runtime_dependencies)

libmath_library = env.SharedLibrary('math', objects)

libmath_module = libmath_library
Export('libmath_module')
