# SPDX-License-Identifier: BSD-3-Clause
"""
libmath - Math library build configuration.
"""

from SCons.Script import Dir, Export

from scripts.scons.utility import GlobSources

Import('UsermodeEnv')

Env = UsermodeEnv.Clone()

Srcpath = Dir('#usr/libmath').abspath

Env.Append(
    CCFLAGS=['-fPIC'],
    CFLAGS=['-fPIC'],
    CXXFLAGS=['-fPIC'],
    LINKFLAGS=[
        '-shared',
        '-Wl,-soname,libmath.so',
    ],
    CPATH=[Srcpath],
    CPPPATH=[Srcpath],
    ASFLAGS=['-I', Srcpath + '/', '-f', 'elf'],
)

Sources = GlobSources(Srcpath)
Objects = Env.SharedObject(Sources)

LibmathLibrary = Env.SharedLibrary('math', Objects)

LibmathModule = LibmathLibrary
Export('LibmathModule')
