# SPDX-License-Identifier: BSD-3-Clause
from SCons.Script import SConscript
Import('sources')

SConscript('devfs/SConscript', exports='sources')
SConscript('disk/SConscript', exports='sources')
SConscript('fat/SConscript', exports='sources')
SConscript('fd/SConscript', exports='sources')
SConscript('misc/SConscript', exports='sources')
SConscript('vfs/SConscript', exports='sources')
