# SPDX-License-Identifier: BSD-3-Clause

from SCons.Script import File, Return


Import('Sources')
Import('CoreSources')


CoreSources += [
	File('core.S'),
]


BootSector = File('boot.S')
Return('BootSector')
