# SPDX-License-Identifier: BSD-3-Clause
from SCons.Script import File, SConscript
Import('Sources')

Sources += [
    File('cmdline.c'),
    File('elf.c'),
    File('sys.c'),
]

SConscript('kmod/SConscript', exports='Sources')
