# SPDX-License-Identifier: BSD-3-Clause
from SCons.Script import SConscript
Import('TargetEnvironment')
Import('Sources')

Architecture = TargetEnvironment['BuildArch']
SConscript(f'{Architecture}/SConscript', exports='Sources')
