# SPDX-License-Identifier: BSD-3-Clause
from SCons.Script import SConscript
Import('TargetEnvironment')
Import('Sources')

Architecture = TargetEnvironment['build.arch']
SConscript(f'{Architecture}/SConscript', exports='Sources')
