# SPDX-License-Identifier: BSD-3-Clause
"""
sh - Shell application build configuration.
"""

from SCons.Script import Dir, Export

from scripts.scons.utility import GlobSources

Import('usermode_env')
Import('runtime_dependencies')

env = usermode_env.Clone()

srcpath = Dir('#usr/sh').abspath

env.Append(
    CPATH=[srcpath],
    CPPPATH=[srcpath],
)

sources = GlobSources(srcpath)
objects = env.Object(sources)
env.Depends(objects, runtime_dependencies)

sh_executable = env.Program('sh', objects)

sh_module = sh_executable
Export('sh_module')
